### ISSUE TITLE
Add ENV of every environment

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/gy-accounts#10]
The purpose of this issue is to add environment variables for every current environment (Local and Production) to the GY Accounts API.

# Tasks

- [x] Create both environment variables files.
- [x] Add the production file to the deployment.
- [x] Store them safely.

In order for this issue to be closed, all tasks should be completed.
