### ISSUE TITLE
GY Accounts v2

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/gy-accounts#4]
The purpose of this issue is to redesign and update GY Accounts to its v2. This version being completely incompatible with the old v1.

# Tasks
- [x] Delete the old system of authentication and cipher functionalities.
- [x] Delete the MongoDB database.
- [x] Migrate functionality to Hexagonal Architecture.
- [x] Migrate authentication to Auth0 using Email/username and Password along with Google Authentication.
- [x] Implement achievements functionality inside this service.
- [x] Redesign exception management based on the success of [#10](https://github.com/GY-CODING/fallofthegods-data/issues/10).
- [x] Update Postman contracts.
- [x] Update documentation.

In order for this issue to be closed, all tasks should be completed.
